version: '3.8'

services:
  minecraft-server:
    build: .
    container_name: meu-minecraft
    ports:
      - "25565:25565"
    volumes:
      - ./meu-servidor-minecraft:/mc  # opcional, se quiser persistir dados externos
    restart: unless-stopped
